# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


deep-remove-regex:
- "/java-shopping-merchant-reports/grpc-google-.*/src"
- "/java-shopping-merchant-reports/proto-google-.*/src"
- "/java-shopping-merchant-reports/google-.*/src"
- "/java-shopping-merchant-reports/samples/snippets/generated"

deep-preserve-regex:
- "/java-shopping-merchant-reports/google-.*/src/test/java/com/google/cloud/.*/v.*/it/IT.*Test.java"

deep-copy-regex:
- source: "/google/shopping/merchant/reports/(v.*)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/java-shopping-merchant-reports/$1/proto-google-shopping-merchant-reports-$1/src"
- source: "/google/shopping/merchant/reports/(v.*)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/java-shopping-merchant-reports/$1/grpc-google-shopping-merchant-reports-$1/src"
- source: "/google/shopping/merchant/reports/(v.*)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/java-shopping-merchant-reports/$1/google-shopping-merchant-reports/src"
- source: "/google/shopping/merchant/reports/(v.*)/.*-java/samples/snippets/generated"
  dest: "/owl-bot-staging/java-shopping-merchant-reports/$1/samples/snippets/generated"


api-name: merchantapi