# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


deep-remove-regex:
- "/java-speech/samples/snippets/generated"
- "/java-speech/grpc-google-.*/src"
- "/java-speech/proto-google-.*/src"
- "/java-speech/google-.*/src"

deep-preserve-regex:
- "/java-speech/google-.*/src/test/java/com/google/cloud/.*/v.*/it/IT.*Test.java"
- "/java-speech/proto-google-cloud-speech-v1beta1/"
- "/java-speech/grpc-google-cloud-speech-v1beta1/"
- "/java-speech/google-cloud-speech/src/main/java/com/google/cloud/speech/v1beta1"
- "/java-speech/google-cloud-speech/src/test/java/com/google/cloud/speech/v1beta1"
- "/java-speech/google-cloud-speech/src/test/java/com/google/cloud/speech/v1/SpeechSmokeTest.java"
- "/java-speech/google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/SpeechSmokeTest.java"
- "/java-speech/google-cloud-speech/src/test/resources/hello.flac"
- "/java-speech/google-cloud-speech/src/test/resources/META-INF/native-image/"


deep-copy-regex:
- source: "/google/cloud/speech/(v.*)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/java-speech/$1/proto-google-cloud-speech-$1/src"
- source: "/google/cloud/speech/(v.*)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/java-speech/$1/grpc-google-cloud-speech-$1/src"
- source: "/google/cloud/speech/(v.*)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/java-speech/$1/google-cloud-speech/src"
- source: "/google/cloud/speech/(v.*)/.*-java/samples/snippets/generated"
  dest: "/owl-bot-staging/java-speech/$1/samples/snippets/generated"

api-name: speech
